require 'rails_helper'

module HiveMindTv
  RSpec.describe Plugin, type: :model do
    describe '#name' do
      # Names are generated by the Elite planet name generator by Ian Bell and
      # David Braben. The 3x2-byte 'random' seed comes from the MAC address.
      # Certain MACs should return known planet names.
      it 'gets the name Lave' do
        dev = Plugin.create('macs' => ['ad:38:14:9c:15:1d'])
        expect(dev.name).to eq 'Lave'
      end
    end
  end
end
